In [8]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
# Data Preprocessing
# Data Preprocessing
# Data Preprocessing
# Data Preprocessing
# Data Preprocessing
# Data Preprocessing
# Data Preprocessing

In [9]:
df = pd.read_csv('Churn_Modelling.csv')

In [10]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [11]:
df.describe

<bound method NDFrame.describe of       RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumO

In [20]:
X = df.iloc[:,3:-1].values
y = df.iloc[:, -1].values

In [21]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [22]:
print(y)

[1 0 1 ... 1 1 0]


In [23]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [24]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [26]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [27]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [28]:
from sklearn.model_selection import train_test_splittest_split

In [30]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

In [31]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [32]:
# Building ANN
# Building ANN
# Building ANN
# Building ANN
# Building ANN
# Building ANN
# Building ANN

In [33]:
ann = tf.keras.models.Sequential()

In [34]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [35]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [36]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [37]:
#Training the ANN
#Training the ANN
#Training the ANN
#Training the ANN
#Training the ANN
#Training the ANN
#Training the ANN
#Training the ANN

In [38]:
ann.compile(optimizer='adam' ,loss='binary_crossentropy' ,metrics=['accuracy'])

In [39]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
210/210 [==============================] - 3s 4ms/step - loss: 0.6588 - accuracy: 0.6588
Epoch 2/100
210/210 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7949
Epoch 3/100
210/210 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.8036
Epoch 4/100
210/210 [==============================] - 1s 4ms/step - loss: 0.4512 - accuracy: 0.8097
Epoch 5/100
210/210 [==============================] - 1s 4ms/step - loss: 0.4410 - accuracy: 0.8103
Epoch 6/100
210/210 [==============================] - 1s 4ms/step - loss: 0.4332 - accuracy: 0.8122
Epoch 7/100
210/210 [==============================] - 1s 4ms/step - loss: 0.4274 - accuracy: 0.8164
Epoch 8/100
210/210 [==============================] - 1s 4ms/step - loss: 0.4209 - accuracy: 0.8169
Epoch 9/100
210/210 [==============================] - 1s 4ms/step - loss: 0.4156 - accuracy: 0.8193
Epoch 10/100
210/210 [==============================] - 1s 4ms/step - loss: 0.4094 - accura

210/210 [==============================] - 1s 5ms/step - loss: 0.3380 - accuracy: 0.8609
Epoch 82/100
210/210 [==============================] - 1s 4ms/step - loss: 0.3374 - accuracy: 0.8627
Epoch 83/100
210/210 [==============================] - 1s 4ms/step - loss: 0.3375 - accuracy: 0.8601
Epoch 84/100
210/210 [==============================] - 1s 4ms/step - loss: 0.3372 - accuracy: 0.8633
Epoch 85/100
210/210 [==============================] - 1s 5ms/step - loss: 0.3374 - accuracy: 0.8631
Epoch 86/100
210/210 [==============================] - 1s 4ms/step - loss: 0.3367 - accuracy: 0.8621
Epoch 87/100
210/210 [==============================] - 1s 4ms/step - loss: 0.3364 - accuracy: 0.8634
Epoch 88/100
210/210 [==============================] - 1s 4ms/step - loss: 0.3368 - accuracy: 0.8621
Epoch 89/100
210/210 [==============================] - 1s 4ms/step - loss: 0.3365 - accuracy: 0.8640
Epoch 90/100
210/210 [==============================] - 1s 4ms/step - loss: 0.3365 - accuracy: 

In [41]:
# Making the Predictions and Evaluating the Model
# Making the Predictions and Evaluating the Model
# Making the Predictions and Evaluating the Model
# Making the Predictions and Evaluating the Model
# Making the Predictions and Evaluating the Model
# Making the Predictions and Evaluating the Model
# Making the Predictions and Evaluating the Model
# Making the Predictions and Evaluating the Model
# Making the Predictions and Evaluating the Model

In [46]:
# Predicting for a customer with following Data
#Geography = France
#Credit Score = 600
#Gender = Male
#Age = 40
#Tenure = 3
#Balance = $60000
#Number of products = 2
#Have a credit card = Yes
#Active Member = Yes
#Estimated Salary = $50000
#Will he leave the bank?


print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

1/1 [==============================] - 0s 45ms/step
[[0.03104412]]


In [47]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 46ms/step
[[False]]


In [50]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

104/104 [==============================] - 0s 2ms/step
[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [53]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2501  119]
 [ 337  343]]


0.8618181818181818